<?php

function scdprimo_help($path, $arg) {
  switch ($path) {
    case "admin/help#scdprimo":
      return '<p>' . t("Various search forms for Primo, Scopus and Pubmed") . '</p>';
      break;
  }
} 

function scdprimo_block_info() {
  $blocks['primo_global'] = array(
    'info' => t('Recherche Primo globale'), 
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['primo_recherche'] = array(
    'info' => t('Recherche Primo pour la Recherche'), 
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

function scdprimo_recherche_tabs() {

  $uadoc = drupal_get_form('scdprimo_uadoc_form');
  $scopus = drupal_get_form('scdprimo_scopus_form');
  $pubmed = drupal_get_form('scdprimo_pubmed_form');
  $manioc = drupal_get_form('scdprimo_manioc_form');
  $out = "";

  $out .= '<div class="row">';

  $out .= '<div id="recherchetabs" class="col-xs-12 col-sm-9">';
  $out .= '<div class="shadow-container">';
  $out .= '<ul class="nav nav-tabs" role="tablist">';
  $out .= '<li role="presentation" class="active"><a href="#uadoc" aria-controls="uadoc" role="tab" data-toggle="tab">UADoc</a></li>';
  $out .= '<li role="presentation"               ><a href="#scopus" aria-controls="scopus" role="tab" data-toggle="tab">Scopus</a></li>';
  $out .= '<li role="presentation"               ><a href="#pubmed" aria-controls="pubmed" role="tab" data-toggle="tab">PubMed</a></li>';
  $out .= '<li role="presentation"               ><a href="#manioc" aria-controls="manioc" role="tab" data-toggle="tab">Manioc</a></li>';
  $out .= "</ul>";
  $out .= '<div class="tab-content">';

    $out .= '<div role="tabpanel" class="tab-pane active" id="uadoc">';
    $out .= '<table class="table table-bordered">';
    $out .= '<tr>';
    $out .= '<td colspan="3">' . drupal_render($uadoc) . '</td>';
    $out .= '</tr>';
    $out .= '<tr class="visible-xs">';
    $out .= '<td class="col-xs-4"><a href="/ejournals">Revues A-Z</a></td>';
    $out .= '<td class="col-xs-4"><a href="/ressources-electroniques">Ttes ressources</a></td>';
    $out .= '<td class="col-xs-4"><a href="https://www.istex.fr/chercheur/">ISTEX</a></td>';
    $out .= "</tr>";
    $out .= "</table>";
    $out .= "</div>";

    $out .= '<div role="tabpanel" class="tab-pane" id="scopus">';
    $out .= '<table class="table table-bordered">';
    $out .= '<tr>';
    $out .= '<td colspan="3">' . drupal_render($scopus) . '</td>';
    $out .= '</tr>';
    $out .= '<tr class="visible-xs">';
    $out .= '<td class="col-xs-4"><a href="/ejournals">Revues A-Z</a></td>';
    $out .= '<td class="col-xs-4"><a href="/ressources-electroniques">Ttes ressources</a></td>';
    $out .= '<td class="col-xs-4"><a href="https://www.istex.fr/chercheur/">ISTEX</a></td>';
    $out .= "</tr>";
    $out .= "</table>";
    $out .= "</div>";

    $out .= '<div role="tabpanel" class="tab-pane" id="pubmed">';
    $out .= '<table class="table table-bordered">';
    $out .= '<tr>';
    $out .= '<td colspan="3">' . drupal_render($pubmed) . '</td>';
    $out .= '</tr>';
    $out .= '<tr class="visible-xs">';
    $out .= '<td class="col-xs-4"><a href="/ejournals">Revues A-Z</a></td>';
    $out .= '<td class="col-xs-4"><a href="/ressources-electroniques">Ttes ressources</a></td>';
    $out .= '<td class="col-xs-4"><a href="https://www.istex.fr/chercheur/">ISTEX</a></td>';
    $out .= "</tr>";
    $out .= "</table>";
    $out .= "</div>";
	
    $out .= '<div role="tabpanel" class="tab-pane" id="manioc">';
    $out .= '<table class="table table-bordered">';
    $out .= '<tr>';
    $out .= '<td colspan="3">' . drupal_render($manioc) . '</td>';
    $out .= '</tr>';
    $out .= '<tr class="visible-xs">';
    $out .= '<td class="col-xs-4"><a href="/ejournals">Revues A-Z</a></td>';
    $out .= '<td class="col-xs-4"><a href="/ressources-electroniques">Ttes ressources</a></td>';
    $out .= '<td class="col-xs-4"><a href="https://www.istex.fr/chercheur/">ISTEX</a></td>';
    $out .= "</tr>";
    $out .= "</table>";
    $out .= "</div>";

  $out .= '</div>';
  $out .= '</div>';
  $out .= '</div>';

  $out .= '<div class="col-sm-3 hidden-xs">';
  $out .= '<a href="/ejournals" class="arrowed"><span class="visible-xs">Revues A-Z</span><span class="hidden-xs">Revues de A à Z</span></a>';
  $out .= '<a href="/ressources-electroniques" class="arrowed"><span class="visible-xs">Ttes ressources</span><span class="hidden-xs">Toutes les ressources en ligne</span></a>';
  $out .= '<a href="https://www.istex.fr/chercheur/" class="arrowed"><span class="visible-xs">ISTEX</span><span class="hidden-xs">ISTEX services aux chercheurs</span></a>';
  $out .= '</div>';

  $out .= '</div>';

  return $out;
}

function scdprimo_block_view($delta = '') {
  switch($delta) {
    case 'primo_global':
      $block['content'] = drupal_get_form('scdprimo_global_form');
      break;
    case 'primo_recherche':
      $block['content'] = scdprimo_recherche_tabs(); 
      break;
  }

  return $block;
}

function scdprimo_global_form($form_state) {
  $form['query'] = array(
    '#type' => 'textfield',
    '#title' => t('Search'),
    '#attributes' => array(
      'placeholder' => t('Livres, articles, DVD, etc...'),
      'onclick' => 'this.form.target="_blank";return true;',
    ),
    '#theme_wrappers' => array(),
    '#prefix' => '<div class="input-group input-group-lg">',
    '#required' => TRUE,
  );

  //$form['institution']  = array('#type' => 'hidden', '#value' => 'UAG',       );
  $form['vid']          = array('#type' => 'hidden', '#value' => '33UAG_INST:33UAG_INST',       );
  $form['search_scope'] = array('#type' => 'hidden', '#value' => 'MyInst_and_CI');
  $form['tab']          = array('#type' => 'hidden', '#value' => 'Everything');

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => '<span class="glyphicon glyphicon-search visible-xs" aria-hidden="true"></span> <span class="hidden-xs">Chercher</span>',
    '#prefix' => '<span class="input-group-btn">',
    '#suffix' => '</span></div>',
  );

  return $form;
}

function scdprimo_global_form_submit($form, &$form_state) {
  
  unset($form_state['values']['submit']);
  unset($form_state['values']['form_build_id']);
  unset($form_state['values']['form_id']);
  unset($form_state['values']['op']);
  unset($form_state['values']['form_token']);
  /*$form_state['values']['submit'] = null;
  $form_state['values']['form_build_id'] = null;
  $form_state['values']['form_id'] = null;
  $form_state['values']['op'] = null;
  $form_state['values']['form_token'] = null;*/
  
  $form_state['values']['query'] = 'any,contains,' . $form_state['values']['query'];
  $url = 'https://uag.primo.exlibrisgroup.com/discovery/search' .
    url(NULL, array(
      'query' => $form_state['values'],
      'external' => TRUE,
    ));

  drupal_goto($url); 
}

function scdprimo_scopus_form() {
  $form['sot']  = array('#type' => 'hidden', '#value' => 'b');
  $form['s']  = array('#type' => 'hidden', '#value' => 'TITLE-ABS-KEY');

  $form['searchterm1'] = array(
    '#type' => 'textfield',
    '#title' => t('Search'),
    '#attributes' => array(
      'placeholder' => t('Livres, articles, DVD, etc...'),
      'onclick' => 'this.form.target="_blank";return true;',
    ),
    '#theme_wrappers' => array(),
    '#prefix' => '<div class="input-group input-group-lg">',
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => '<span class="glyphicon glyphicon-search visible-xs" aria-hidden="true"></span> <span class="hidden-xs">Chercher</span>',
    '#prefix' => '<span class="input-group-btn">',
    '#suffix' => '</span></div>',
  );

  return $form;
}

function scdprimo_pubmed_form() {
  $form['term'] = array(
    '#type' => 'textfield',
    '#title' => t('Search'),
    '#attributes' => array(
      'placeholder' => t('Livres, articles, DVD, etc...'),
      'onclick' => 'this.form.target="_blank";return true;',
    ),
    '#theme_wrappers' => array(),
    '#prefix' => '<div class="input-group input-group-lg">',
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => '<span class="glyphicon glyphicon-search visible-xs" aria-hidden="true"></span> <span class="hidden-xs">Chercher</span>',
    '#prefix' => '<span class="input-group-btn">',
    '#suffix' => '</span></div>',
  );

  return $form;
}

function scdprimo_uadoc_form() {
  $form['offset']  = array('#type' => 'hidden', '#value' => '0',       );
  $form['vid']          = array('#type' => 'hidden', '#value' => '33UAG_INST:33UAG_INST',       );
  $form['search_scope'] = array('#type' => 'hidden', '#value' => 'MyInst_and_CI');
  $form['tab']          = array('#type' => 'hidden', '#value' => 'Everything');
  $form['subform']          = array('#type' => 'hidden', '#value' => 'Trouver');
  $form['sortby']          = array('#type' => 'hidden', '#value' => 'rank');
  $form['lang']          = array('#type' => 'hidden', '#value' => 'fr_FR');
  
  
  $form['query'] = array(
    '#type' => 'textfield',
    '#title' => t('Search'),
    '#attributes' => array(
      'placeholder' => t('Livres, articles, DVD, etc...'),
      'onclick' => 'this.form.target="_blank";return true;',
    ),
    '#theme_wrappers' => array(),
    '#prefix' => '<div class="input-group input-group-lg">',
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => '<span class="glyphicon glyphicon-search visible-xs" aria-hidden="true"></span> <span class="hidden-xs">Chercher</span>',
    '#prefix' => '<span class="input-group-btn">',
    '#suffix' => '</span></div>',
  );

  return $form;
}

function scdprimo_uadoc_form_submit($form, &$form_state) {
  
  unset($form_state['values']['submit']);
  unset($form_state['values']['form_build_id']);
  unset($form_state['values']['form_id']);
  unset($form_state['values']['op']);
  unset($form_state['values']['form_token']);
    	
  $form_state['values']['query'] = 'any,contains,' . $form_state['values']['query'];
  $url = 'https://uag.primo.exlibrisgroup.com/discovery/search' .
    url(NULL, array(
      'query' => $form_state['values'],
      'external' => TRUE,
    ));

  drupal_goto($url); 
}

function scdprimo_manioc_form() {
  $form['a']  = array('#type' => 'hidden', '#value' => 'q',       );
  $form['r']          = array('#type' => 'hidden', '#value' => '1',       );
  $form['hs'] = array('#type' => 'hidden', '#value' => '1');
  $form['e']          = array('#type' => 'hidden', '#value' => 'q-11000-00---off-0portail-bnpm,fichiers,portail,catalogu,etudesc1,recherch,patrimon,images,bnf,dloc,tramil,esclaves,thsesenl,ifremer,haluag,uwi-01-1----0-10-0---0---0direct-10---4-------0-1l--11-fr-Zz-1---20-about---00-3-1-00-0-0-11-0-0utfZz-8-00');
  $form['fqf']          = array('#type' => 'hidden', '#value' => 'DC',       );
  $form['t']          = array('#type' => 'hidden', '#value' => '0',       );
  
  $form['q'] = array(
    '#type' => 'textfield',
    '#title' => t('Search'),
    '#attributes' => array(
      'placeholder' => t('Titre, auteurs, sujets'),
      'onclick' => 'this.form.target="_blank";return true;',
    ),
    '#theme_wrappers' => array(),
    '#prefix' => '<div class="input-group input-group-lg">',
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => '<span class="glyphicon glyphicon-search visible-xs" aria-hidden="true"></span> <span class="hidden-xs">Chercher</span>',
    '#prefix' => '<span class="input-group-btn">',
    '#suffix' => '</span></div>',
  );

  return $form;
}

function scdprimo_manioc_form_submit($form, &$form_state) {
	
	
  $form_state['values']['submit'] = null;
  $form_state['values']['op'] = null;	

  $url = 'http://www.manioc.org/gsdl/cgi-bin/library' .
    url(NULL, array(
      'query' => $form_state['values'],
      'external' => TRUE,
    ));

  drupal_goto($url); 
}

function scdprimo_scopus_form_submit($form, &$form_state) {

  $new_s = $form['s']['#value']."(".$form['searchterm1']['#value'].")";
  
  $form_state['values']['s'] = $new_s;
  
      
  $form_state['values']['submit'] = null;
  $form_state['values']['op'] = null;
  $url = 'http://bu-services.univ-antilles.fr:5000/login?url=https://www.scopus.com/results/results.uri' .
    url(NULL, array(
      'query' => $form_state['values'],
      'external' => TRUE,
    ));
		
  drupal_goto($url); 
}

function scdprimo_pubmed_form_submit($form, &$form_state) {
  $url = 'http://www.ncbi.nlm.nih.gov/pubmed' .
    url(NULL, array(
      'query' => $form_state['values'],
      'external' => TRUE,
    ));

  drupal_goto($url); 
}

?>
