<?php

function scdprimo_help($path, $arg) {
  switch ($path) {
    case "admin/help#scdprimo":
      return '<p>' . t("Help text") . '</p>';
      break;
  }
} 

function scdprimo_menu() {

  $items[] = array(
    'path' => 'primo-global',
    'title' => 'Rechercher',
    'page callback' => 'scdprimo_global',
    'access callback' => TRUE,
  );

  $items[] = array(
    'path' => 'primo-martinique',
    'title' => 'Rechercher',
    'page callback' => 'scdprimo_martinique',
    'access callback' => TRUE,
  );

  $items[] = array(
    'path' => 'primo-guadeloupe',
    'title' => 'Rechercher',
    'page callback' => 'scdprimo_guadeloupe',
    'access callback' => TRUE,
  );

  return $items;
}

function scdprimo_global() {
  return drupal_get_form('scdprimo_global_form');
}

function scdprimo_global_form($form_state) {

  $form['query'] = array(
    '#type' => 'textfield',
    '#title' => t('Search'),
    '#required' => TRUE,
  );

  $form['institution']  = array('#type' => 'hidden', '#value' => 'UAG',        );
  $form['vid']          = array('#type' => 'hidden', '#value' => 'UAG',        );
  $form['search_scope'] = array('#type' => 'hidden', '#value' => 'UAG_HORIZON' );
  $form['tab']          = array('#type' => 'hidden', '#value' => 'default_tab' );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );

  return $form;
}

function scdprimo_global_form_submit($form, &$form_state) {
  $form_state['values']['query'] = 'any,contains,' . $form_state['values']['query'];
  $url = 'http://chipri03bleu.hosted.exlibrisgroup.com:1701/primo_library/libweb/action/dlSearch.do' .
    url(NULL, array(
      'query' => $form_state['values'],
      'external' => TRUE,
    ));
  drupal_goto($url); 
}

function scdprimo_martinique() {
}

function scdprimo_guadeloupe() {
}

?>
